swagger: "2.0"
info:

  version: "1.0.0"
  title: "Swagger Poststore"

host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "Article"
schemes:
- "https"
- "http"
paths:
  /Articles:
    post:
      tags:
      - "Post"
      summary: "Add a new post to the store"
      description: ""
      operationId: "addPost"
      consumes:
      - "application/json"
      - "application/yml"
      produces:
      - "application/yml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Post object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "405":
          description: "Invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"